### ISSUE TITLE
Latest release missing change to remove click

### ISSUE THREAD

**Issue by jkwayf** [spaceone-dev/grpc_requests#41]
Somehow the latest release does not have the change to remove click:
https://github.com/spaceone-dev/grpc_requests/compare/v0.1.1...master

**Comment by jkwayf** [comment]
I think this is fixed - just needs a new release here: https://pypi.org/project/grpc-requests/

**Comment by wesky93** [comment]
Originally, I tried to deploy it right away, but the test is failing to see if the specification has changed in the latest version of grpcio.
However, since the previous test was successful, it will be distributed today for users of the previous version. In the future, I will limit the grpc version or resolve compatibility issues until it is properly supported and release additional releases.
